var startingBoard = [
    {
        row:8,
        col:"a",
        piece:"rook",
        team:"black"
    },
    {
        row:8,
        col:"b",
        piece:"knight",
        team:"black"
    },
    {
        row:8,
        col:"c",
        piece:"bishop",
        team:"black"
    },
    {
        row:8,
        col:"d",
        piece:"king",
        team:"black"
    },
    {
        row:8,
        col:"e",
        piece:"queen",
        team:"black"
    },
    {
        row:8,
        col:"f",
        piece:"bishop",
        team:"black"
    },
    {
        row:8,
        col:"g",
        piece:"knight",
        team:"black"
    },
    {
        row:8,
        col:"h",
        piece:"rook",
        team:"black"
    },
    {
        row:7,
        col:"a",
        piece:"pawn",
        team:"black"
    },
    {
        row:7,
        col:"b",
        piece:"pawn",
        team:"black"
    },
    {
        row:7,
        col:"c",
        piece:"pawn",
        team:"black"
    },
    {
        row:7,
        col:"d",
        piece:"pawn",
        team:"black"
    },
    {
        row:7,
        col:"e",
        piece:"pawn",
        team:"black"
    },
    {
        row:7,
        col:"f",
        piece:"pawn",
        team:"black"
    },
    {
        row:7,
        col:"g",
        piece:"pawn",
        team:"black"
    },
    {
        row:7,
        col:"h",
        piece:"pawn",
        team:"black"
    },
    {
        row:1,
        col:"a",
        piece:"rook",
        team:"white"
    },
    {
        row:1,
        col:"b",
        piece:"knight",
        team:"white"
    },
    {
        row:1,
        col:"c",
        piece:"bishop",
        team:"white"
    },
    {
        row:1,
        col:"d",
        piece:"king",
        team:"white"
    },
    {
        row:1,
        col:"e",
        piece:"queen",
        team:"white"
    },
    {
        row:1,
        col:"f",
        piece:"bishop",
        team:"white"
    },
    {
        row:1,
        col:"g",
        piece:"knight",
        team:"white"
    },
    {
        row:1,
        col:"h",
        piece:"rook",
        team:"white"
    },
    {
        row:2,
        col:"a",
        piece:"pawn",
        team:"white"
    },
    {
        row:2,
        col:"b",
        piece:"pawn",
        team:"white"
    },
    {
        row:2,
        col:"c",
        piece:"pawn",
        team:"white"
    },
    {
        row:2,
        col:"d",
        piece:"pawn",
        team:"white"
    },
    {
        row:2,
        col:"e",
        piece:"pawn",
        team:"white"
    },
    {
        row:2,
        col:"f",
        piece:"pawn",
        team:"white"
    },
    {
        row:2,
        col:"g",
        piece:"pawn",
        team:"white"
    },
    {
        row:2,
        col:"h",
        piece:"pawn",
        team:"white"
    }
];